# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rvfl_forward <- function(X, W) {
    .Call('_RFRVFL_rvfl_forward', PACKAGE = 'RFRVFL', X, W)
}

estimate_output_weights <- function(O, y) {
    .Call('_RFRVFL_estimate_output_weights', PACKAGE = 'RFRVFL', O, y)
}

